version: '3.8'

services:
  site:
    #command: jekyll serve --watch --force_polling --incremental
    #command: jekyll serve --watch
    command: jekyll serve --watch --drafts
    #image: jekyll/jekyll:3.8
    image: jekyll/jekyll
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
